package net.suncaper.demo.mapper;

import java.util.List;
import net.suncaper.demo.common.domain.Achievement;
import net.suncaper.demo.common.domain.AchievementExample;
import org.apache.ibatis.annotations.Param;

public interface AchievementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    long countByExample(AchievementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    int deleteByExample(AchievementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    int insert(Achievement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    int insertSelective(Achievement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    List<Achievement> selectByExample(AchievementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    Achievement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Achievement record, @Param("example") AchievementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Achievement record, @Param("example") AchievementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Achievement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    int updateByPrimaryKey(Achievement record);
}