package net.suncaper.demo.mapper;

import java.util.List;
import net.suncaper.demo.common.domain.Apply;
import net.suncaper.demo.common.domain.ApplyExample;
import org.apache.ibatis.annotations.Param;

public interface ApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:14:36 GMT+08:00 2021
     */
    long countByExample(ApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:14:36 GMT+08:00 2021
     */
    int deleteByExample(ApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:14:36 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:14:36 GMT+08:00 2021
     */
    int insert(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:14:36 GMT+08:00 2021
     */
    int insertSelective(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:14:36 GMT+08:00 2021
     */
    List<Apply> selectByExample(ApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:14:36 GMT+08:00 2021
     */
    Apply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:14:36 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Apply record, @Param("example") ApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:14:36 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Apply record, @Param("example") ApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:14:36 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:14:36 GMT+08:00 2021
     */
    int updateByPrimaryKey(Apply record);
}