package net.suncaper.demo.mapper;

import java.util.List;
import net.suncaper.demo.common.domain.Dossier;
import net.suncaper.demo.common.domain.DossierExample;
import org.apache.ibatis.annotations.Param;

public interface DossierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dossier
     *
     * @mbg.generated Thu Mar 04 10:56:28 GMT+08:00 2021
     */
    long countByExample(DossierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dossier
     *
     * @mbg.generated Thu Mar 04 10:56:28 GMT+08:00 2021
     */
    int deleteByExample(DossierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dossier
     *
     * @mbg.generated Thu Mar 04 10:56:28 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dossier
     *
     * @mbg.generated Thu Mar 04 10:56:28 GMT+08:00 2021
     */
    int insert(Dossier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dossier
     *
     * @mbg.generated Thu Mar 04 10:56:28 GMT+08:00 2021
     */
    int insertSelective(Dossier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dossier
     *
     * @mbg.generated Thu Mar 04 10:56:28 GMT+08:00 2021
     */
    List<Dossier> selectByExample(DossierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dossier
     *
     * @mbg.generated Thu Mar 04 10:56:28 GMT+08:00 2021
     */
    Dossier selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dossier
     *
     * @mbg.generated Thu Mar 04 10:56:28 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Dossier record, @Param("example") DossierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dossier
     *
     * @mbg.generated Thu Mar 04 10:56:28 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Dossier record, @Param("example") DossierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dossier
     *
     * @mbg.generated Thu Mar 04 10:56:28 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Dossier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dossier
     *
     * @mbg.generated Thu Mar 04 10:56:28 GMT+08:00 2021
     */
    int updateByPrimaryKey(Dossier record);
}