package net.suncaper.demo.mapper;

import java.util.List;
import net.suncaper.demo.common.domain.Employ;
import net.suncaper.demo.common.domain.EmployExample;
import org.apache.ibatis.annotations.Param;

public interface EmployMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbg.generated Sat Feb 27 14:32:24 CST 2021
     */
    long countByExample(EmployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbg.generated Sat Feb 27 14:32:24 CST 2021
     */
    int deleteByExample(EmployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbg.generated Sat Feb 27 14:32:24 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbg.generated Sat Feb 27 14:32:24 CST 2021
     */
    int insert(Employ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbg.generated Sat Feb 27 14:32:24 CST 2021
     */
    int insertSelective(Employ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbg.generated Sat Feb 27 14:32:24 CST 2021
     */
    List<Employ> selectByExample(EmployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbg.generated Sat Feb 27 14:32:24 CST 2021
     */
    Employ selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbg.generated Sat Feb 27 14:32:24 CST 2021
     */
    int updateByExampleSelective(@Param("record") Employ record, @Param("example") EmployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbg.generated Sat Feb 27 14:32:24 CST 2021
     */
    int updateByExample(@Param("record") Employ record, @Param("example") EmployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbg.generated Sat Feb 27 14:32:24 CST 2021
     */
    int updateByPrimaryKeySelective(Employ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbg.generated Sat Feb 27 14:32:24 CST 2021
     */
    int updateByPrimaryKey(Employ record);
}