package net.suncaper.demo.mapper;

import java.util.List;
import net.suncaper.demo.common.domain.License;
import net.suncaper.demo.common.domain.LicenseExample;
import org.apache.ibatis.annotations.Param;

public interface LicenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    long countByExample(LicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    int deleteByExample(LicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    int deleteByPrimaryKey(Integer companyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    int insert(License record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    int insertSelective(License record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    List<License> selectByExample(LicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    License selectByPrimaryKey(Integer companyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") License record, @Param("example") LicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    int updateByExample(@Param("record") License record, @Param("example") LicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    int updateByPrimaryKeySelective(License record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    int updateByPrimaryKey(License record);
}