package net.suncaper.demo.mapper;

import java.util.List;
import net.suncaper.demo.common.domain.Mistake;
import net.suncaper.demo.common.domain.MistakeExample;
import org.apache.ibatis.annotations.Param;

public interface MistakeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mistake
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    long countByExample(MistakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mistake
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int deleteByExample(MistakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mistake
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mistake
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int insert(Mistake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mistake
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int insertSelective(Mistake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mistake
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    List<Mistake> selectByExample(MistakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mistake
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    Mistake selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mistake
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Mistake record, @Param("example") MistakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mistake
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Mistake record, @Param("example") MistakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mistake
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Mistake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mistake
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int updateByPrimaryKey(Mistake record);
}