package net.suncaper.demo.mapper;

import java.util.List;
import net.suncaper.demo.common.domain.Resign;
import net.suncaper.demo.common.domain.ResignExample;
import org.apache.ibatis.annotations.Param;

public interface ResignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    long countByExample(ResignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int deleteByExample(ResignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int insert(Resign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int insertSelective(Resign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    List<Resign> selectByExample(ResignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    Resign selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Resign record, @Param("example") ResignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Resign record, @Param("example") ResignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Resign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resign
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    int updateByPrimaryKey(Resign record);
}