server:
  port: 8280
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml,classpath:/mybatis/mapper/extend/*.xml


spring:
  datasource:
     url: jdbc:mysql://localhost:3306/managment?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
     username: root
     password: 1234
     driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    net/suncaper/demo: debug

