server:
  port: 8280
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml,classpath:/mybatis/mapper/extend/*.xml


spring:
  datasource:
     url: jdbc:mysql://localhost:3306/managment?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
     username: root
     password: admin
     driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    # password:
    lettuce:
      poll:
        minIdle: 1
        maxIdle: 10
        maxWait: 3
        maxActive: 8

logging:
  level:
    net/suncaper/demo: debug

