package net.suncaper.demo.common.domain;

import java.util.Date;

public class Achievement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievement.Id
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievement.createDate
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievement.employ_id
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    private Integer employId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievement.achieve_content
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    private String achieveContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public Achievement(Integer id, Date createdate, Integer employId, String achieveContent) {
        this.id = id;
        this.createdate = createdate;
        this.employId = employId;
        this.achieveContent = achieveContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public Achievement() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievement.Id
     *
     * @return the value of achievement.Id
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievement.Id
     *
     * @param id the value for achievement.Id
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievement.createDate
     *
     * @return the value of achievement.createDate
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievement.createDate
     *
     * @param createdate the value for achievement.createDate
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievement.employ_id
     *
     * @return the value of achievement.employ_id
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public Integer getEmployId() {
        return employId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievement.employ_id
     *
     * @param employId the value for achievement.employ_id
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public void setEmployId(Integer employId) {
        this.employId = employId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievement.achieve_content
     *
     * @return the value of achievement.achieve_content
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public String getAchieveContent() {
        return achieveContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievement.achieve_content
     *
     * @param achieveContent the value for achievement.achieve_content
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public void setAchieveContent(String achieveContent) {
        this.achieveContent = achieveContent == null ? null : achieveContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Achievement other = (Achievement) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreatedate() == null ? other.getCreatedate() == null : this.getCreatedate().equals(other.getCreatedate()))
            && (this.getEmployId() == null ? other.getEmployId() == null : this.getEmployId().equals(other.getEmployId()))
            && (this.getAchieveContent() == null ? other.getAchieveContent() == null : this.getAchieveContent().equals(other.getAchieveContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreatedate() == null) ? 0 : getCreatedate().hashCode());
        result = prime * result + ((getEmployId() == null) ? 0 : getEmployId().hashCode());
        result = prime * result + ((getAchieveContent() == null) ? 0 : getAchieveContent().hashCode());
        return result;
    }
}