package net.suncaper.demo.common.domain;

public class Apply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.Id
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.workerid
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    private Integer workerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.companyid
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    private Integer companyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.isConsent
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    private Integer isconsent;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    public Apply(Integer id, Integer workerid, Integer companyid, Integer isconsent) {
        this.id = id;
        this.workerid = workerid;
        this.companyid = companyid;
        this.isconsent = isconsent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    public Apply() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.Id
     *
     * @return the value of apply.Id
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.Id
     *
     * @param id the value for apply.Id
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.workerid
     *
     * @return the value of apply.workerid
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    public Integer getWorkerid() {
        return workerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.workerid
     *
     * @param workerid the value for apply.workerid
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    public void setWorkerid(Integer workerid) {
        this.workerid = workerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.companyid
     *
     * @return the value of apply.companyid
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.companyid
     *
     * @param companyid the value for apply.companyid
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.isConsent
     *
     * @return the value of apply.isConsent
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    public Integer getIsconsent() {
        return isconsent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.isConsent
     *
     * @param isconsent the value for apply.isConsent
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    public void setIsconsent(Integer isconsent) {
        this.isconsent = isconsent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Apply other = (Apply) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getWorkerid() == null ? other.getWorkerid() == null : this.getWorkerid().equals(other.getWorkerid()))
            && (this.getCompanyid() == null ? other.getCompanyid() == null : this.getCompanyid().equals(other.getCompanyid()))
            && (this.getIsconsent() == null ? other.getIsconsent() == null : this.getIsconsent().equals(other.getIsconsent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Mon Mar 01 19:52:06 GMT+08:00 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getWorkerid() == null) ? 0 : getWorkerid().hashCode());
        result = prime * result + ((getCompanyid() == null) ? 0 : getCompanyid().hashCode());
        result = prime * result + ((getIsconsent() == null) ? 0 : getIsconsent().hashCode());
        return result;
    }
}