package net.suncaper.demo.common.domain;

import java.util.Date;

public class Employ {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employ.Id
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employ.Company_id
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employ.Worker_id
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    private String workerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employ.start_date
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employ.end_date
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public Employ(Integer id, String companyId, String workerId, Date startDate, Date endDate) {
        this.id = id;
        this.companyId = companyId;
        this.workerId = workerId;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public Employ() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employ.Id
     *
     * @return the value of employ.Id
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employ.Id
     *
     * @param id the value for employ.Id
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employ.Company_id
     *
     * @return the value of employ.Company_id
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employ.Company_id
     *
     * @param companyId the value for employ.Company_id
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employ.Worker_id
     *
     * @return the value of employ.Worker_id
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public String getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employ.Worker_id
     *
     * @param workerId the value for employ.Worker_id
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public void setWorkerId(String workerId) {
        this.workerId = workerId == null ? null : workerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employ.start_date
     *
     * @return the value of employ.start_date
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employ.start_date
     *
     * @param startDate the value for employ.start_date
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employ.end_date
     *
     * @return the value of employ.end_date
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employ.end_date
     *
     * @param endDate the value for employ.end_date
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Employ other = (Employ) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getWorkerId() == null ? other.getWorkerId() == null : this.getWorkerId().equals(other.getWorkerId()))
            && (this.getStartDate() == null ? other.getStartDate() == null : this.getStartDate().equals(other.getStartDate()))
            && (this.getEndDate() == null ? other.getEndDate() == null : this.getEndDate().equals(other.getEndDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getWorkerId() == null) ? 0 : getWorkerId().hashCode());
        result = prime * result + ((getStartDate() == null) ? 0 : getStartDate().hashCode());
        result = prime * result + ((getEndDate() == null) ? 0 : getEndDate().hashCode());
        return result;
    }
}