package net.suncaper.demo.common.domain;

import java.util.Date;

public class Grade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.Id
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.createDate
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.employ_id
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    private Integer employId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.content
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    private Integer content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public Grade(Integer id, Date createdate, Integer employId, Integer content) {
        this.id = id;
        this.createdate = createdate;
        this.employId = employId;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public Grade() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.Id
     *
     * @return the value of grade.Id
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.Id
     *
     * @param id the value for grade.Id
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.createDate
     *
     * @return the value of grade.createDate
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.createDate
     *
     * @param createdate the value for grade.createDate
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.employ_id
     *
     * @return the value of grade.employ_id
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public Integer getEmployId() {
        return employId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.employ_id
     *
     * @param employId the value for grade.employ_id
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public void setEmployId(Integer employId) {
        this.employId = employId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.content
     *
     * @return the value of grade.content
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public Integer getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.content
     *
     * @param content the value for grade.content
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    public void setContent(Integer content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Grade other = (Grade) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreatedate() == null ? other.getCreatedate() == null : this.getCreatedate().equals(other.getCreatedate()))
            && (this.getEmployId() == null ? other.getEmployId() == null : this.getEmployId().equals(other.getEmployId()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Thu Mar 04 19:34:50 GMT+08:00 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreatedate() == null) ? 0 : getCreatedate().hashCode());
        result = prime * result + ((getEmployId() == null) ? 0 : getEmployId().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }
}