package net.suncaper.demo.common.domain;

public class License {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license.companyid
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    private Integer companyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license.name
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license.credit
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    private String credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license.ifCreditValid
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    private String ifcreditvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license.capital
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    private String capital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license.owner
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license.companyType
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    private String companytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license.establishDate
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    private String establishdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license.expirationDate
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    private String expirationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license.address
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license.businessScope
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    private String businessscope;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public License(Integer companyid, String name, String credit, String ifcreditvalid, String capital, String owner, String companytype, String establishdate, String expirationdate, String address, String businessscope) {
        this.companyid = companyid;
        this.name = name;
        this.credit = credit;
        this.ifcreditvalid = ifcreditvalid;
        this.capital = capital;
        this.owner = owner;
        this.companytype = companytype;
        this.establishdate = establishdate;
        this.expirationdate = expirationdate;
        this.address = address;
        this.businessscope = businessscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public License() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license.companyid
     *
     * @return the value of license.companyid
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license.companyid
     *
     * @param companyid the value for license.companyid
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license.name
     *
     * @return the value of license.name
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license.name
     *
     * @param name the value for license.name
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license.credit
     *
     * @return the value of license.credit
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public String getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license.credit
     *
     * @param credit the value for license.credit
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public void setCredit(String credit) {
        this.credit = credit == null ? null : credit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license.ifCreditValid
     *
     * @return the value of license.ifCreditValid
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public String getIfcreditvalid() {
        return ifcreditvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license.ifCreditValid
     *
     * @param ifcreditvalid the value for license.ifCreditValid
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public void setIfcreditvalid(String ifcreditvalid) {
        this.ifcreditvalid = ifcreditvalid == null ? null : ifcreditvalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license.capital
     *
     * @return the value of license.capital
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public String getCapital() {
        return capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license.capital
     *
     * @param capital the value for license.capital
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public void setCapital(String capital) {
        this.capital = capital == null ? null : capital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license.owner
     *
     * @return the value of license.owner
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license.owner
     *
     * @param owner the value for license.owner
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license.companyType
     *
     * @return the value of license.companyType
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public String getCompanytype() {
        return companytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license.companyType
     *
     * @param companytype the value for license.companyType
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public void setCompanytype(String companytype) {
        this.companytype = companytype == null ? null : companytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license.establishDate
     *
     * @return the value of license.establishDate
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public String getEstablishdate() {
        return establishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license.establishDate
     *
     * @param establishdate the value for license.establishDate
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public void setEstablishdate(String establishdate) {
        this.establishdate = establishdate == null ? null : establishdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license.expirationDate
     *
     * @return the value of license.expirationDate
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public String getExpirationdate() {
        return expirationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license.expirationDate
     *
     * @param expirationdate the value for license.expirationDate
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public void setExpirationdate(String expirationdate) {
        this.expirationdate = expirationdate == null ? null : expirationdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license.address
     *
     * @return the value of license.address
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license.address
     *
     * @param address the value for license.address
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license.businessScope
     *
     * @return the value of license.businessScope
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public String getBusinessscope() {
        return businessscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license.businessScope
     *
     * @param businessscope the value for license.businessScope
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    public void setBusinessscope(String businessscope) {
        this.businessscope = businessscope == null ? null : businessscope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        License other = (License) that;
        return (this.getCompanyid() == null ? other.getCompanyid() == null : this.getCompanyid().equals(other.getCompanyid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCredit() == null ? other.getCredit() == null : this.getCredit().equals(other.getCredit()))
            && (this.getIfcreditvalid() == null ? other.getIfcreditvalid() == null : this.getIfcreditvalid().equals(other.getIfcreditvalid()))
            && (this.getCapital() == null ? other.getCapital() == null : this.getCapital().equals(other.getCapital()))
            && (this.getOwner() == null ? other.getOwner() == null : this.getOwner().equals(other.getOwner()))
            && (this.getCompanytype() == null ? other.getCompanytype() == null : this.getCompanytype().equals(other.getCompanytype()))
            && (this.getEstablishdate() == null ? other.getEstablishdate() == null : this.getEstablishdate().equals(other.getEstablishdate()))
            && (this.getExpirationdate() == null ? other.getExpirationdate() == null : this.getExpirationdate().equals(other.getExpirationdate()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getBusinessscope() == null ? other.getBusinessscope() == null : this.getBusinessscope().equals(other.getBusinessscope()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license
     *
     * @mbg.generated Sat Mar 06 13:31:28 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCompanyid() == null) ? 0 : getCompanyid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCredit() == null) ? 0 : getCredit().hashCode());
        result = prime * result + ((getIfcreditvalid() == null) ? 0 : getIfcreditvalid().hashCode());
        result = prime * result + ((getCapital() == null) ? 0 : getCapital().hashCode());
        result = prime * result + ((getOwner() == null) ? 0 : getOwner().hashCode());
        result = prime * result + ((getCompanytype() == null) ? 0 : getCompanytype().hashCode());
        result = prime * result + ((getEstablishdate() == null) ? 0 : getEstablishdate().hashCode());
        result = prime * result + ((getExpirationdate() == null) ? 0 : getExpirationdate().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getBusinessscope() == null) ? 0 : getBusinessscope().hashCode());
        return result;
    }
}