package net.suncaper.demo.common.domain;

import java.util.Date;

public class Mistake {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mistake.Id
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mistake.date
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mistake.employ_id
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    private Integer employId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mistake.mistake_content
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    private String mistakeContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mistake
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public Mistake(Integer id, Date date, Integer employId, String mistakeContent) {
        this.id = id;
        this.date = date;
        this.employId = employId;
        this.mistakeContent = mistakeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mistake
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public Mistake() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mistake.Id
     *
     * @return the value of mistake.Id
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mistake.Id
     *
     * @param id the value for mistake.Id
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mistake.date
     *
     * @return the value of mistake.date
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mistake.date
     *
     * @param date the value for mistake.date
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mistake.employ_id
     *
     * @return the value of mistake.employ_id
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public Integer getEmployId() {
        return employId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mistake.employ_id
     *
     * @param employId the value for mistake.employ_id
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public void setEmployId(Integer employId) {
        this.employId = employId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mistake.mistake_content
     *
     * @return the value of mistake.mistake_content
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public String getMistakeContent() {
        return mistakeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mistake.mistake_content
     *
     * @param mistakeContent the value for mistake.mistake_content
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    public void setMistakeContent(String mistakeContent) {
        this.mistakeContent = mistakeContent == null ? null : mistakeContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mistake
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Mistake other = (Mistake) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDate() == null ? other.getDate() == null : this.getDate().equals(other.getDate()))
            && (this.getEmployId() == null ? other.getEmployId() == null : this.getEmployId().equals(other.getEmployId()))
            && (this.getMistakeContent() == null ? other.getMistakeContent() == null : this.getMistakeContent().equals(other.getMistakeContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mistake
     *
     * @mbg.generated Mon Mar 01 16:16:43 GMT+08:00 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDate() == null) ? 0 : getDate().hashCode());
        result = prime * result + ((getEmployId() == null) ? 0 : getEmployId().hashCode());
        result = prime * result + ((getMistakeContent() == null) ? 0 : getMistakeContent().hashCode());
        return result;
    }
}