package net.suncaper.demo.common.domain;

public class Worker {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.Id
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.Name
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.IdCard
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.Account
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.Password
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.Sex
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.Birth
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    private Integer birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.Belong
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    private String belong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.IdentifyFlag
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    private Integer identifyflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.isEvaluate
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    private Integer isevaluate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.Education
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.Major
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.PhoneNumber
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    private String phonenumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public Worker(Integer id, String name, String idcard, String account, String password, String sex, Integer birth, String belong, Integer identifyflag, Integer isevaluate, String education, String major, String phonenumber) {
        this.id = id;
        this.name = name;
        this.idcard = idcard;
        this.account = account;
        this.password = password;
        this.sex = sex;
        this.birth = birth;
        this.belong = belong;
        this.identifyflag = identifyflag;
        this.isevaluate = isevaluate;
        this.education = education;
        this.major = major;
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public Worker() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.Id
     *
     * @return the value of worker.Id
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.Id
     *
     * @param id the value for worker.Id
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.Name
     *
     * @return the value of worker.Name
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.Name
     *
     * @param name the value for worker.Name
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.IdCard
     *
     * @return the value of worker.IdCard
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.IdCard
     *
     * @param idcard the value for worker.IdCard
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.Account
     *
     * @return the value of worker.Account
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.Account
     *
     * @param account the value for worker.Account
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.Password
     *
     * @return the value of worker.Password
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.Password
     *
     * @param password the value for worker.Password
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.Sex
     *
     * @return the value of worker.Sex
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.Sex
     *
     * @param sex the value for worker.Sex
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.Birth
     *
     * @return the value of worker.Birth
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public Integer getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.Birth
     *
     * @param birth the value for worker.Birth
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public void setBirth(Integer birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.Belong
     *
     * @return the value of worker.Belong
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public String getBelong() {
        return belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.Belong
     *
     * @param belong the value for worker.Belong
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public void setBelong(String belong) {
        this.belong = belong == null ? null : belong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.IdentifyFlag
     *
     * @return the value of worker.IdentifyFlag
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public Integer getIdentifyflag() {
        return identifyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.IdentifyFlag
     *
     * @param identifyflag the value for worker.IdentifyFlag
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public void setIdentifyflag(Integer identifyflag) {
        this.identifyflag = identifyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.isEvaluate
     *
     * @return the value of worker.isEvaluate
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public Integer getIsevaluate() {
        return isevaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.isEvaluate
     *
     * @param isevaluate the value for worker.isEvaluate
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public void setIsevaluate(Integer isevaluate) {
        this.isevaluate = isevaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.Education
     *
     * @return the value of worker.Education
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.Education
     *
     * @param education the value for worker.Education
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.Major
     *
     * @return the value of worker.Major
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.Major
     *
     * @param major the value for worker.Major
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.PhoneNumber
     *
     * @return the value of worker.PhoneNumber
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.PhoneNumber
     *
     * @param phonenumber the value for worker.PhoneNumber
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Worker other = (Worker) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getIdcard() == null ? other.getIdcard() == null : this.getIdcard().equals(other.getIdcard()))
            && (this.getAccount() == null ? other.getAccount() == null : this.getAccount().equals(other.getAccount()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getBirth() == null ? other.getBirth() == null : this.getBirth().equals(other.getBirth()))
            && (this.getBelong() == null ? other.getBelong() == null : this.getBelong().equals(other.getBelong()))
            && (this.getIdentifyflag() == null ? other.getIdentifyflag() == null : this.getIdentifyflag().equals(other.getIdentifyflag()))
            && (this.getIsevaluate() == null ? other.getIsevaluate() == null : this.getIsevaluate().equals(other.getIsevaluate()))
            && (this.getEducation() == null ? other.getEducation() == null : this.getEducation().equals(other.getEducation()))
            && (this.getMajor() == null ? other.getMajor() == null : this.getMajor().equals(other.getMajor()))
            && (this.getPhonenumber() == null ? other.getPhonenumber() == null : this.getPhonenumber().equals(other.getPhonenumber()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Wed Feb 17 10:38:19 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getIdcard() == null) ? 0 : getIdcard().hashCode());
        result = prime * result + ((getAccount() == null) ? 0 : getAccount().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getBirth() == null) ? 0 : getBirth().hashCode());
        result = prime * result + ((getBelong() == null) ? 0 : getBelong().hashCode());
        result = prime * result + ((getIdentifyflag() == null) ? 0 : getIdentifyflag().hashCode());
        result = prime * result + ((getIsevaluate() == null) ? 0 : getIsevaluate().hashCode());
        result = prime * result + ((getEducation() == null) ? 0 : getEducation().hashCode());
        result = prime * result + ((getMajor() == null) ? 0 : getMajor().hashCode());
        result = prime * result + ((getPhonenumber() == null) ? 0 : getPhonenumber().hashCode());
        return result;
    }
}